version: "1"
services:
  express_backend:
    container_name: express_backend
    build: .
    depends_on:
      - postgres
    environment:
      - EXTERNAL_PORT=8080
      - PGUSER=test
      - PGPASSWORD=test
      - PGDATABASE=db
      - PGHOST=postgres # NAME OF THE SERVICE
      - PORT: 3000
    ports:
      - "3000:3000"
    command: npm run serve
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1:{}